### PR TITLE
Update with Flatpak instructions

### PR DESCRIPTION
**Pull request by fanuch**
Added some clarification and guidance around Flatpak Steam installations so no one else gets #538

### CODE REVIEW

**Comment by bmeulmeester** [comment]
Bumping this as this is essential information for Steam Deck users.

**Comment by Tallion-07** [comment]
Tested with Debian 12 Total flatpak install (steam, protontricks, (SEEdit added in MO2) LOOT) 
directory used /home/USERNAME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/

This worked straight out of the box, I have tried several "Guides" over several Days, and none worked, and It would not launch MO2 in conjunction with SkyrimSE to inject mods into game.

Using the above Directory path and BANG! worked first time out of the box!

Unable to Launch skse64_loader.exe, SkyrimSE.exe or _SkyrimSELauncher.exe
Able to Launch CreationKit.exe, SSEEdit.exe & SSEEditQuickAutoClean.exe from MO2

So I would consider this Critical for more than just SteamDeck users & Possibly Debian Base Linux as this got it running on Debian 12 (Ubuntu users?)

Tested using MO2 2.4.4
Would Upgrading to MO2 2.5.0 work? or would it break stuff?

**Comment by rockerbacon** [comment]
This works for a few cases (not the Steam Deck, btw, since Steam Deck doesn't flatpak Steam), but is far too incomplete. Here is a short summary of directory requirements:

- Protontricks must have Flatpak permissions to access your Steam libraries
- Steam must have Flatpak permissions to access MO2 and your Steam libraries
- The Steam runtime must have permissions to access MO2 and your Steam libraries
- MO2 must be installed within the same filesystem as the game it is managing

There has never been a goal to document directory permission issues because it would be too much documentation that users simply won't read. This would work better on a separate troubleshooting document (which we currently don't have but we can include).

The proper solution is automatically verifying possible issues and automatically applying the necessary solutions.

**Comment by rockerbacon** [comment]
Install location issues will be discussed in #656 before action is taken.

**Pull request closed without merging**
