### PR TITLE
Update Mod Organizer 2 to v2.4.4

### PR DESCRIPTION
**Pull request by rockerbacon**
Also fixed wrong script return generating incorrect error messages.

### CODE REVIEW

**Comment by rockerbacon** [comment]
Updating it seems to cause problems with the FOMOD module:

```
Unhandled Exception:
System.InvalidProgramException: Invalid IL code in <Module>:InstallerFomodCSharp.settings (InstallerFomodCSharp modopt(System.Runtime.CompilerServices.IsConst)* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),QList<MOBase::PluginSetting>*): IL_0053: add       


  at (wrapper native-to-managed) <Module>.InstallerFomodCSharp.settings(InstallerFomodCSharp modopt(System.Runtime.CompilerServices.IsConst)* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),QList<MOBase::PluginSetting>*)
```

**Comment by rockerbacon** [comment]
Quick search indicates this might be related to .NET. Need to check later if using `dotnet48` instead of what's provided by Steam changes anything.

**Comment by kleshas** [comment]
Fails here too.

**Comment by rockerbacon** [comment]
Adding `dotnet48` to the compatdata broke the prefix, Wine complains about version mismatches when trying to run anything. That one is new, `dotnet48` was used in the past without problems.

**Comment by trevorgunn** [comment]
When I tried this last August, I ran into the same issue of the prefix breaking. But I just tried again today and I was able to install dotnet48 and run Mod Organizer 2.4.1 without any apparent issue.

I wish I could say what has changed between now and then. But it looks like there might still be hope for updating past 2.2.2.1.

This is on Arch Linux, I had to edit the .yml https://github.com/rockerbacon/lutris-skyrimse-installers/blob/076fe7cd13f7c774717dd3b05727dbba8de69b0d/installers/modorganizer2.yml#L320 to point to `/usr/bin/winetricks/` to avoid the checksum issue (#61).

So if anyone else wants to test this:
1. make sure you have the latest version of this installer installed (2.8.6 as of when I tested this).
2. make sure you have the latest version of protontricks/winetricks installed (I'm running PT version 1.5.0 and WT version 2021-02-06)
3. accept that there still might be some risk that installing dotnet48 will break your prefix and you will have to reinstall everything (I sure hope not, but I can't make any promises)
4. install dotnet48 using protontricks
5. install/unpack Mod Organizer v2.4.1 (or later?) somewhere, I chose `$HOME/Games/MO241/`
6. edit `$HOME/Games/mod-organizer-2/run.sh` so it points at the newer version of MO.

Possibly using the system winetricks in the installer rather than the lutris version was also important to getting this not to break.

**Comment by Continous** [comment]
I was able to get v2.4.1 to launch once dotnet48 was installed. Installing it actually worked fine, though it took a fairly long time and threw boku errors. Oddly enough, I was only able to get dotnet48 to install if ran with the "-q" parameter, not when ran normally. It seems to be run-of-the-mill MSI issues on wine's end.

**Comment by kleshas** [comment]
That almost works for me - ran winetricks -f -q dotnet48 on the prefix, and it completed. 2.4.1 and 2.4.2 (latest) loaded up enough to get to the initial setup screens asking for portable instances etc. but always crashed on trying to load the "installer_fomod_csharp.dll" and "installer_omod.dll" plugins, even after blacklisting or skipping them.

**Comment by OskyEdz** [comment]
> That almost works for me - ran winetricks -f -q dotnet48 on the prefix, and it completed. 2.4.1 and 2.4.2 (latest) loaded up enough to get to the initial setup screens asking for portable instances etc. but always crashed on trying to load the "installer_fomod_csharp.dll" and "installer_omod.dll" plugins, even after blacklisting or skipping them.

I managed to start MO 2.4.2 this way after removing thoses two dll's. My thinking was that there where not needed in the original 2.2.2 that came with the installer. 

Delete installer_fomod_csharp.dll" and "installer_omod.dll" from the plugins folder. And press skip/blacklist while starting MO for the installer_omod plugin.

**Comment by OskyEdz** [comment]
@trevorgunn 

> https://github.com/rockerbacon/lutris-skyrimse-installers/blob/076fe7cd13f7c774717dd3b05727dbba8de69b0d/installers/modorganizer2.yml#L320
> 
> to point to `/usr/bin/winetricks/` to avoid the checksum issue (#61).
> 
> Possibly using the system winetricks in the installer rather than the lutris version was also important to getting this not to break.

I'm on Ubuntu 21.04.
PT: 1.6.0
WT: 20210206-next
I also found success after a long while. And this part about changing the winetricks was key. 

Note to others: It's `/usr/bin/winetricks` not `/usr/bin/winetricks/`  

I also used protontricks --gui to install dotnet48 (It also required me to install dotnet40 for some reason)
I tried running vcrun2019 at the same time but I had to exit the gui and run it again to install that.

Btw. I'm curious how you installed/unpacked the installer?
I had to figure out protontricks prefix path and then run `winprefix=<path> wine ModOrganizer.exe`

The biggest problem right now is to get download links to work and not crash when a internet link is clicked...

**Comment by trevorgunn** [comment]
@OskyEdz ModOrganizer gives you both a zip file and an installer, the zip file can simply be extracted.

If you want to run apps inside the Proton prefix (i.e. with Proton), I recommend using the `proton-launcher.sh` script (`.local/share/modorganizer2/`) or editing `games/mod-organizer-2/run.sh` to launch the right exe file.

**Comment by OskyEdz** [comment]
@trevorgunn 

Aha, I'll make sure to pick up that zip-file!

I've been trying to get the app to run with the run script and modified the exe path.

If I run the run.sh from the terminal it starts up, but if I use lutris to start the run.sh the app crash to some error. (I don't remember the exact number right now).

I'm trying to use a nxm link script by [monomachos](https://youtu.be/r0vjAqRjP-M) , but I'm mixing up what is what.

I think I need to run a esync compatible version of wine to make it work, I've done a bit too much testing on my main machine and I have multiple prefixes and wine versions...

I've had problems where MO can't find the game-data and other times where it opens a previous attempt at MO, I just need to reset all the prefixes an clean up everything. I haven't even done any modding yet so there is nothing to lose.

**Comment by CtrlAltLilith** [comment]
https://github.com/CtrlAltLilith/lutris-skyrimse-installers/commit/79a3b3c1bd5fce42c589fcb7d9f71bf61ed95109 Worked locally, with latest Proton GE

**Comment by rockerbacon** [comment]
Previous issues with `dotnet48` were related to how winetricks were applied to the prefix. The new installer uses protontricks, which makes everything easier.

I've briefly tested 2.4.4 and everything seems to be working fine. I'll leave this PR here for a bit so more people can test it.

**Pull request merged**
